ileliczb = input("Ile liczb chcesz odgadnąć?")
ileliczb = int(ileliczb)
print (ileliczb)
maksliczba = input("Jaka jest maksymalna losowana liczba?")
maksliczba = int(maksliczba)
print (maksliczba)
#print ("Wytypuj ",ileliczb," z ",maksliczba," liczb: ")
print("Wytypuj %d z %d liczb: " % (ileliczb,maksliczba))